author: "Martin Hoang"
facebook: "https://www.facebook.com/martin.hog"
twitter: "https://twitter.com/HoangHog"
github: "https://github.com/hoanghog"


exclude: ['README.md'] 
encoding: utf-8

collections:
  hobbies:
    output: true

baseurl: 

gems:
  - jemoji

